package handler

import (
	"context"
	"fmt"
	"strings"

	"github.com/ffimnsr/koios/internal/tasks"
)

func taskCandidatePatch(title *string, details *string, owner *string, dueAt *int64) tasks.CandidatePatch {
	return tasks.CandidatePatch{
		Title:   title,
		Details: details,
		Owner:   owner,
		DueAt:   dueAt,
	}
}

func taskPatch(title *string, details *string, owner *string, dueAt *int64, snoozeUntil *int64) tasks.TaskPatch {
	return tasks.TaskPatch{
		Title:       title,
		Details:     details,
		Owner:       owner,
		DueAt:       dueAt,
		SnoozeUntil: snoozeUntil,
	}
}

func (h *Handler) taskCandidateCreate(peerID string, input tasks.CandidateInput, ctx context.Context) (map[string]any, error) {
	if h.taskStore == nil {
		return nil, fmt.Errorf("tasks are not enabled")
	}
	candidate, err := h.taskStore.QueueCandidate(ctx, peerID, input)
	if err != nil {
		return nil, err
	}
	return map[string]any{"ok": true, "candidate": candidate}, nil
}

func (h *Handler) taskCandidateExtract(peerID, text string, provenance tasks.CandidateProvenance, ctx context.Context) (map[string]any, error) {
	if h.taskStore == nil {
		return nil, fmt.Errorf("tasks are not enabled")
	}
	text = strings.TrimSpace(text)
	if text == "" {
		return nil, fmt.Errorf("text is required")
	}
	provenance = normalizeTaskCandidateProvenance(provenance)
	candidates, err := h.taskStore.ExtractAndQueue(ctx, peerID, text, provenance)
	if err != nil {
		return nil, err
	}
	return map[string]any{
		"ok":           true,
		"count":        len(candidates),
		"candidates":   candidates,
		"capture_kind": provenance.CaptureKind,
	}, nil
}

func normalizeTaskCandidateProvenance(provenance tasks.CandidateProvenance) tasks.CandidateProvenance {
	provenance.CaptureKind = strings.TrimSpace(provenance.CaptureKind)
	if provenance.CaptureKind == "" {
		provenance.CaptureKind = tasks.CandidateCaptureExternalExtract
	}
	provenance.SourceSessionKey = strings.TrimSpace(provenance.SourceSessionKey)
	if provenance.SourceExcerpt == "" {
		provenance.SourceExcerpt = provenance.SourceSessionKey
	}
	provenance.SourceExcerpt = strings.TrimSpace(provenance.SourceExcerpt)
	return provenance
}

func (h *Handler) taskCandidateList(peerID string, limit int, status string, ctx context.Context) (map[string]any, error) {
	if h.taskStore == nil {
		return nil, fmt.Errorf("tasks are not enabled")
	}
	if limit <= 0 {
		limit = 50
	}
	candidates, err := h.taskStore.ListCandidates(ctx, peerID, limit, tasks.CandidateStatus(status))
	if err != nil {
		return nil, err
	}
	manualCount := 0
	autoGeneratedCount := 0
	byCaptureKind := make(map[string]int)
	for _, candidate := range candidates {
		kind := strings.TrimSpace(candidate.CaptureKind)
		if kind == "" {
			kind = tasks.CandidateCaptureManual
		}
		byCaptureKind[kind]++
		switch kind {
		case tasks.CandidateCaptureManual:
			manualCount++
		case tasks.CandidateCaptureAutoTurnExtract, tasks.CandidateCaptureExternalExtract:
			autoGeneratedCount++
		}
	}
	return map[string]any{
		"count":                len(candidates),
		"candidates":           candidates,
		"status":               strings.TrimSpace(status),
		"manual_count":         manualCount,
		"auto_generated_count": autoGeneratedCount,
		"capture_kinds":        byCaptureKind,
	}, nil
}

func (h *Handler) taskCandidateEdit(peerID, id string, patch tasks.CandidatePatch, ctx context.Context) (map[string]any, error) {
	if h.taskStore == nil {
		return nil, fmt.Errorf("tasks are not enabled")
	}
	if strings.TrimSpace(id) == "" {
		return nil, fmt.Errorf("id is required")
	}
	candidate, err := h.taskStore.EditCandidate(ctx, peerID, id, patch)
	if err != nil {
		return nil, err
	}
	return map[string]any{"ok": true, "candidate": candidate}, nil
}

func (h *Handler) taskCandidateApprove(peerID, id string, patch tasks.CandidatePatch, reason string, ctx context.Context) (map[string]any, error) {
	if h.taskStore == nil {
		return nil, fmt.Errorf("tasks are not enabled")
	}
	if strings.TrimSpace(id) == "" {
		return nil, fmt.Errorf("id is required")
	}
	candidate, task, err := h.taskStore.ApproveCandidate(ctx, peerID, id, patch, reason)
	if err != nil {
		return nil, err
	}
	return map[string]any{"ok": true, "candidate": candidate, "task": task}, nil
}

func (h *Handler) taskCandidateReject(peerID, id, reason string, ctx context.Context) (map[string]any, error) {
	if h.taskStore == nil {
		return nil, fmt.Errorf("tasks are not enabled")
	}
	if strings.TrimSpace(id) == "" {
		return nil, fmt.Errorf("id is required")
	}
	candidate, err := h.taskStore.RejectCandidate(ctx, peerID, id, reason)
	if err != nil {
		return nil, err
	}
	return map[string]any{"ok": true, "candidate": candidate}, nil
}

func (h *Handler) taskList(peerID string, limit int, status string, ctx context.Context) (map[string]any, error) {
	if h.taskStore == nil {
		return nil, fmt.Errorf("tasks are not enabled")
	}
	if limit <= 0 {
		limit = 50
	}
	tasksList, err := h.taskStore.ListTasks(ctx, peerID, limit, tasks.TaskStatus(status))
	if err != nil {
		return nil, err
	}
	return map[string]any{"count": len(tasksList), "tasks": tasksList, "status": strings.TrimSpace(status)}, nil
}

func (h *Handler) taskGet(peerID, id string, ctx context.Context) (map[string]any, error) {
	if h.taskStore == nil {
		return nil, fmt.Errorf("tasks are not enabled")
	}
	if strings.TrimSpace(id) == "" {
		return nil, fmt.Errorf("id is required")
	}
	task, err := h.taskStore.GetTask(ctx, peerID, id)
	if err != nil {
		return nil, err
	}
	return map[string]any{"task": task}, nil
}

func (h *Handler) taskUpdate(peerID, id string, patch tasks.TaskPatch, ctx context.Context) (map[string]any, error) {
	if h.taskStore == nil {
		return nil, fmt.Errorf("tasks are not enabled")
	}
	if strings.TrimSpace(id) == "" {
		return nil, fmt.Errorf("id is required")
	}
	task, err := h.taskStore.UpdateTask(ctx, peerID, id, patch)
	if err != nil {
		return nil, err
	}
	return map[string]any{"ok": true, "task": task}, nil
}

func (h *Handler) taskAssign(peerID, id, owner string, ctx context.Context) (map[string]any, error) {
	task, err := h.taskStore.AssignTask(ctx, peerID, id, owner)
	if err != nil {
		return nil, err
	}
	return map[string]any{"ok": true, "task": task}, nil
}

func (h *Handler) taskSnooze(peerID, id string, until int64, ctx context.Context) (map[string]any, error) {
	task, err := h.taskStore.SnoozeTask(ctx, peerID, id, until)
	if err != nil {
		return nil, err
	}
	return map[string]any{"ok": true, "task": task}, nil
}

func (h *Handler) taskComplete(peerID, id string, ctx context.Context) (map[string]any, error) {
	task, err := h.taskStore.CompleteTask(ctx, peerID, id)
	if err != nil {
		return nil, err
	}
	return map[string]any{"ok": true, "task": task}, nil
}

func (h *Handler) taskReopen(peerID, id string, ctx context.Context) (map[string]any, error) {
	task, err := h.taskStore.ReopenTask(ctx, peerID, id)
	if err != nil {
		return nil, err
	}
	return map[string]any{"ok": true, "task": task}, nil
}
